"""recurrence anchor

Revision ID: bc9bed354278
Revises: 74dd2dcf2b03
Create Date: 2026-05-28 15:35:48.854073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc9bed354278'
down_revision: Union[str, Sequence[str], None] = '74dd2dcf2b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definitions', sa.Column('anchor_weekday', sa.Integer(), nullable=True))
    op.add_column('task_definitions', sa.Column('anchor_day_of_month', sa.Integer(), nullable=True))
    op.drop_column('task_definitions', 'rotation_period_days')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task_definitions', sa.Column('rotation_period_days', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('task_definitions', 'anchor_day_of_month')
    op.drop_column('task_definitions', 'anchor_weekday')
    # ### end Alembic commands ###
